version: '3'

services:
  auth_db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=auth_db
    ports:
      - 3308:3306

  store_db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3307:3306

  adminer:
    image: adminer
    ports:
      - 8080:8080